config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "notes#index"
  resources :notes
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :therapist
  belongs_to :patient
  validates  :patient, presence: true
  validates  :therapist, presence: true
  validates  :raw_notes, presence: true


  def arrange_report
    ReportParsing.new(self)
  end

  def self.stage
    ["STG2", "STG3"]
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :notes
  has_many :patients, through: :notes
end

app/models/therapist.rb
class Therapist < ApplicationRecord
	has_many :notes
	has_many :patients, through: :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)
    respond_to do |format|
      if @note.save
        @note.arrange_report
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:patient_id, :therapist_id, :raw_notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
	def structure_data
    patient_performance = @note.patient_performance
    patient_performance_array = patient_performance.split("|")
    view_array = []
    patient_performance_array.each do |patient_word|
    	hash  = {}
    	hash[patient_word.split(" ").first] = patient_word.split(" ").last
    	view_array << hash
    end
    view_array	
	end

	def get_result(data)
		view_string = ""
		for i in 0..data.length()-1
			string = ""
      string = (data[i]=="+" ? "success" : "unsuccess")
			view_string << string + " "
		end
		view_string	
	end

	def get_noun_result(string)
		if string.present? 
			array  = string.split(" ")
			array.last
		end	
	end

  def get_noun_description(string)
  	array  = string.split(" ")
  	performance = ""
  	for i in 0..array.length-2
      performance << array[i]
		end
		description = performance.gsub(/\s+/, "")
		description_array = []
		for i in 0..description.length-1
			description_array << (description[i]=="+" ? "success" : "unsuccess")
		end
		description_array
  end

  def stage_one_error(string)
  	if string.present?
  		string.split(",")
  	end	
  end	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekickTherapyPartners</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_id, class: "form-label" %>
    <%= form.collection_select :patient_id, Patient.all,:id,:name, include_blank: true,  class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :therapist_id, class: "form-label" %>
    <%= form.collection_select :therapist_id, Therapist.all,:id,:name, include_blank: true,   class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :raw_notes, class: "form-label" %>
    <%= form.text_area :raw_notes, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_stage_one.html.erb
<h4 class="text-center">  Report For Stage One</h4>
</br>
<div class="container">
  <span><b> Patient Name :-</b>
  <span><%= @note.patient.name%></span>
  </br>
  <span><b> Test Type :-</b>
  <span><%= @note.test_type%></span><br><br>
  <h6><b>Test Description</b></h6>
  <% for i in 0..@note.patient_performance.length %>
   <li><%=@note.patient_performance[i]=="+"? "success" : "unsuccess"%></li>
  <% end %><br><br>
  <h6><b>Error To Speak:-</b></h6>
  <% stage_one_error(@note.error).each do |error| %>
  <li><%= error %></li>
  <% end %> 
  <h5> Result: <%=@note.result%> </h5>
  </h6><b>Result has been approved by:-</b> <%=@note.therapist.name%></h6><br><br>
</div>

app/views/notes/_stage_three.html.erb
<h1 class="text-center"> Report </h1>
</br>
<span><b>Patient Name :-</b></span>
<span><%= @note.patient.name%></span>
</br>
<span><b> Test Type :-</b></span>
<span><%= @note.test_type%></h2></span><br><br>
<h5>Test Description</h5>


<div class="container">
  <div class="row">
    <div class="col margin-right">
     <h3>Noun</h3>
		<div><b>Description</b></div>
		<% get_noun_description(@note.n_performance).each do |description| %>
		<div class="container"><li><%=description%></li></div>
		<%end%><br>
		<div><b>Error To Speak:-</b> <%=@note.n_error%></div>
		<div><b>Result:-</b> <%=get_noun_result(@note.n_performance)%> </div>
    </div>
    <div class="col">
      	<h3>Verb</h3>
		<div><b>Description</b></div>
		<% get_noun_description(@note.v_performance).each do |description| %>
		<div class="container"><li><%=description%></li></div>
		<%end%><br>
		<div><b>Error To Speak:-</b> <%=@note.v_error%></div>
		<div><b>Result:-</b><%=get_noun_result(@note.v_performance)%></div>
    </div>
  </div>
<br>
<h5><b>Final Result:-</b> <%=@note.result%> </h5>
</h6><b>Result has been approved by:-</b> <%=@note.therapist.name%></h6><br><br>

app/views/notes/_stage_two.html.erb
<h4 class="text-center"> Report : <%=@note.heading%> </h4>
</br>
<span><b> Patient Name :-</b>
<span><%= @note.patient.name%></span>
</br>
<span><b> Test Type :-</b>
<span><%= @note.test_type%></span><br><br>
<h6><b>Test Description</b></h6>
<table>
  <thead>
    <tr>
      <th >Word</th>
      <th>Result</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% structure_data.each do |data| %>
      <tr>
        <td><%=data.keys[0]%></td>
        <td><%=get_result(data.values[0])%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h6> Result: <%=@note.result%> </h6>
</h6>Result has been approved by: <%=@note.therapist.name%></h6><br><br>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<body class="container">
  <p id="notice"><%= notice %></p>

  <h1>Notes</h1>
  <%= link_to 'New Note', new_note_path, class: "btn btn-info" %><br><br>

  <table>
    <thead>
      <tr>
        <th >Patient</th>
        <th>Therapist</th>
        <th>Raw notes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @notes.each do |note| %>
        <tr>
          <td><%= note.patient.name%></td>
          <td><%= note.therapist.name %></td>
          <td><%= note.raw_notes %></td>
          <td><%= link_to 'Show', note, class: "btn btn-info" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</body>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<body class="container">
  <p id="notice"><%= notice %></p>
  <% if @note.stage=="one" %>
    <%= render "stage_one" %>
  <% elsif @note.stage=="two" %>
    <%= render "stage_two" %>
  <% elsif @note.stage=="three" %>
    <%= render "stage_three" %>
  <% else%>
   <h1>Report doesn't have any format to show.</h1>
  <%end%> 
  <%= link_to 'Back', notes_path, class: "btn btn-info" %>
</body>